extends: eslint:recommended
plugins:
    - node
parserOptions:
    ecmaVersion: 7
env:
    node: true
rules:
    node/no-missing-import: 2
    node/no-missing-require: 2
    node/no-unpublished-import: 2
    node/no-unpublished-require: 2
    node/no-unsupported-features: 
        - 2
        - version: 4
    node/shebang: 2

    comma-dangle:
        - error
        - always-multiline