extends: eslint:recommended
plugins:
    - node
parserOptions:
    ecmaVersion: 7
    sourceType: module
    ecmaFeatures:
        experimentalObjectRestSpread: true
env:
    jest: true
    node: true
globals:
    Promise: true
rules:
    node/no-missing-import: 2
    node/no-missing-require: 2
    node/no-unpublished-import: 2
    node/no-unpublished-require: 2
    node/shebang: 2

    comma-dangle:
        - error
        - always-multiline